### ISSUE TITLE
Order of vector operations

### ISSUE THREAD

**Issue by gilgamec** [dzhus/simple-vec3#2]
There's currently no precedence set for any of the Vec3 operations, so they take place strictly left-associative, i.e.
```
v.^a <+> w.^b == ((v.^a) <+> w).^b
```
I'd suggest that they be given the same precedence as the `Num` operators, i.e. 6 for addition and subtraction, and 7 for multiplication. (That's the same precedence used by `Linear`.)

**Comment by dzhus** [comment]
@gilgamec Hi, this was implemented in simple-vec3-0.5
